### ISSUE TITLE
Question: Support for Shrine 3 derivatives?

### ISSUE THREAD

**Issue by Bandes** [texpert/shrine-lambda#13]
Hi - I am using Shrine 3 and looking into using your plugin. Will this work with the new derivatives plugin? (Replacement for versions) If not, do you plan on updating for Shrine 3?

**Comment by texpert** [comment]
Hi, @Bandes !

Thank you for interest! Honestly, I have not tried it long time, so I don't know is it compatible with Shrine 3.

I hope to have some time soon to try and update it.

**Comment by texpert** [comment]
> Hi - I am using Shrine 3 and looking into using your plugin. Will this work with the new derivatives plugin? (Replacement for versions) If not, do you plan on updating for Shrine 3?

Whew, it got me almost 3 years to upgrade it to work with Shrine 3...

Also, I've changed the gem name for clarity, so now it is a new gem in a new repository - https://github.com/texpert/shrine-aws-lambda/releases/tag/v0.2.0
